#!/usr/bin/python

import sys
from gi.repository import Gio, GLib, UDisks

if __name__ == "__main__":
    filename = sys.argv[1]
    if os.path.exists(filename):
        try:
            passphrase = "lbu"
            
